/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as EnsaiosCasuaisRouteImport } from './routes/ensaios.casuais'
import { Route as EnsaiosCasaisRouteImport } from './routes/ensaios.casais'
import { Route as EnsaiosAniversariosRouteImport } from './routes/ensaios.aniversarios'
import { Route as EnsaiosSlugRouteImport } from './routes/ensaios.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ApiAdminUploadRouteImport } from './routes/api.admin.upload'
import { Route as ApiAdminSessionRouteImport } from './routes/api.admin.session'
import { Route as ApiAdminPublishRouteImport } from './routes/api.admin.publish'
import { Route as ApiAdminLogoutRouteImport } from './routes/api.admin.logout'
import { Route as ApiAdminLoginRouteImport } from './routes/api.admin.login'
import { Route as ApiAdminContentRouteImport } from './routes/api.admin.content'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const EnsaiosCasuaisRoute = EnsaiosCasuaisRouteImport.update({
  id: '/ensaios/casuais',
  path: '/ensaios/casuais',
  getParentRoute: () => rootRouteImport,
} as any)
const EnsaiosCasaisRoute = EnsaiosCasaisRouteImport.update({
  id: '/ensaios/casais',
  path: '/ensaios/casais',
  getParentRoute: () => rootRouteImport,
} as any)
const EnsaiosAniversariosRoute = EnsaiosAniversariosRouteImport.update({
  id: '/ensaios/aniversarios',
  path: '/ensaios/aniversarios',
  getParentRoute: () => rootRouteImport,
} as any)
const EnsaiosSlugRoute = EnsaiosSlugRouteImport.update({
  id: '/ensaios/$slug',
  path: '/ensaios/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAdminUploadRoute = ApiAdminUploadRouteImport.update({
  id: '/api/admin/upload',
  path: '/api/admin/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSessionRoute = ApiAdminSessionRouteImport.update({
  id: '/api/admin/session',
  path: '/api/admin/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPublishRoute = ApiAdminPublishRouteImport.update({
  id: '/api/admin/publish',
  path: '/api/admin/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogoutRoute = ApiAdminLogoutRouteImport.update({
  id: '/api/admin/logout',
  path: '/api/admin/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminContentRoute = ApiAdminContentRouteImport.update({
  id: '/api/admin/content',
  path: '/api/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/como-funciona': typeof ComoFuncionaRoute
  '/contacto': typeof ContactoRoute
  '/portfolio': typeof PortfolioRoute
  '/privacidade': typeof PrivacidadeRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/admin/login': typeof AdminLoginRoute
  '/ensaios/$slug': typeof EnsaiosSlugRoute
  '/ensaios/aniversarios': typeof EnsaiosAniversariosRoute
  '/ensaios/casais': typeof EnsaiosCasaisRoute
  '/ensaios/casuais': typeof EnsaiosCasuaisRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/content': typeof ApiAdminContentRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/publish': typeof ApiAdminPublishRoute
  '/api/admin/session': typeof ApiAdminSessionRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contacto': typeof ContactoRoute
  '/portfolio': typeof PortfolioRoute
  '/privacidade': typeof PrivacidadeRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/admin/login': typeof AdminLoginRoute
  '/ensaios/$slug': typeof EnsaiosSlugRoute
  '/ensaios/aniversarios': typeof EnsaiosAniversariosRoute
  '/ensaios/casais': typeof EnsaiosCasaisRoute
  '/ensaios/casuais': typeof EnsaiosCasuaisRoute
  '/admin': typeof AdminIndexRoute
  '/api/admin/content': typeof ApiAdminContentRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/publish': typeof ApiAdminPublishRoute
  '/api/admin/session': typeof ApiAdminSessionRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/como-funciona': typeof ComoFuncionaRoute
  '/contacto': typeof ContactoRoute
  '/portfolio': typeof PortfolioRoute
  '/privacidade': typeof PrivacidadeRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/admin/login': typeof AdminLoginRoute
  '/ensaios/$slug': typeof EnsaiosSlugRoute
  '/ensaios/aniversarios': typeof EnsaiosAniversariosRoute
  '/ensaios/casais': typeof EnsaiosCasaisRoute
  '/ensaios/casuais': typeof EnsaiosCasuaisRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/content': typeof ApiAdminContentRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/publish': typeof ApiAdminPublishRoute
  '/api/admin/session': typeof ApiAdminSessionRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/como-funciona'
    | '/contacto'
    | '/portfolio'
    | '/privacidade'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sobre'
    | '/admin/login'
    | '/ensaios/$slug'
    | '/ensaios/aniversarios'
    | '/ensaios/casais'
    | '/ensaios/casuais'
    | '/admin/'
    | '/api/admin/content'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/publish'
    | '/api/admin/session'
    | '/api/admin/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/como-funciona'
    | '/contacto'
    | '/portfolio'
    | '/privacidade'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sobre'
    | '/admin/login'
    | '/ensaios/$slug'
    | '/ensaios/aniversarios'
    | '/ensaios/casais'
    | '/ensaios/casuais'
    | '/admin'
    | '/api/admin/content'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/publish'
    | '/api/admin/session'
    | '/api/admin/upload'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/como-funciona'
    | '/contacto'
    | '/portfolio'
    | '/privacidade'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sobre'
    | '/admin/login'
    | '/ensaios/$slug'
    | '/ensaios/aniversarios'
    | '/ensaios/casais'
    | '/ensaios/casuais'
    | '/admin/'
    | '/api/admin/content'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/publish'
    | '/api/admin/session'
    | '/api/admin/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ContactoRoute: typeof ContactoRoute
  PortfolioRoute: typeof PortfolioRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  EnsaiosSlugRoute: typeof EnsaiosSlugRoute
  EnsaiosAniversariosRoute: typeof EnsaiosAniversariosRoute
  EnsaiosCasaisRoute: typeof EnsaiosCasaisRoute
  EnsaiosCasuaisRoute: typeof EnsaiosCasuaisRoute
  ApiAdminContentRoute: typeof ApiAdminContentRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminLogoutRoute: typeof ApiAdminLogoutRoute
  ApiAdminPublishRoute: typeof ApiAdminPublishRoute
  ApiAdminSessionRoute: typeof ApiAdminSessionRoute
  ApiAdminUploadRoute: typeof ApiAdminUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/ensaios/casuais': {
      id: '/ensaios/casuais'
      path: '/ensaios/casuais'
      fullPath: '/ensaios/casuais'
      preLoaderRoute: typeof EnsaiosCasuaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ensaios/casais': {
      id: '/ensaios/casais'
      path: '/ensaios/casais'
      fullPath: '/ensaios/casais'
      preLoaderRoute: typeof EnsaiosCasaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ensaios/aniversarios': {
      id: '/ensaios/aniversarios'
      path: '/ensaios/aniversarios'
      fullPath: '/ensaios/aniversarios'
      preLoaderRoute: typeof EnsaiosAniversariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ensaios/$slug': {
      id: '/ensaios/$slug'
      path: '/ensaios/$slug'
      fullPath: '/ensaios/$slug'
      preLoaderRoute: typeof EnsaiosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/admin/upload': {
      id: '/api/admin/upload'
      path: '/api/admin/upload'
      fullPath: '/api/admin/upload'
      preLoaderRoute: typeof ApiAdminUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/session': {
      id: '/api/admin/session'
      path: '/api/admin/session'
      fullPath: '/api/admin/session'
      preLoaderRoute: typeof ApiAdminSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/publish': {
      id: '/api/admin/publish'
      path: '/api/admin/publish'
      fullPath: '/api/admin/publish'
      preLoaderRoute: typeof ApiAdminPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/logout': {
      id: '/api/admin/logout'
      path: '/api/admin/logout'
      fullPath: '/api/admin/logout'
      preLoaderRoute: typeof ApiAdminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/content': {
      id: '/api/admin/content'
      path: '/api/admin/content'
      fullPath: '/api/admin/content'
      preLoaderRoute: typeof ApiAdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ContactoRoute: ContactoRoute,
  PortfolioRoute: PortfolioRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  EnsaiosSlugRoute: EnsaiosSlugRoute,
  EnsaiosAniversariosRoute: EnsaiosAniversariosRoute,
  EnsaiosCasaisRoute: EnsaiosCasaisRoute,
  EnsaiosCasuaisRoute: EnsaiosCasuaisRoute,
  ApiAdminContentRoute: ApiAdminContentRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminLogoutRoute: ApiAdminLogoutRoute,
  ApiAdminPublishRoute: ApiAdminPublishRoute,
  ApiAdminSessionRoute: ApiAdminSessionRoute,
  ApiAdminUploadRoute: ApiAdminUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
