/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnsaiosCasuaisRouteImport } from './routes/ensaios.casuais'
import { Route as EnsaiosCasaisRouteImport } from './routes/ensaios.casais'
import { Route as EnsaiosAniversariosRouteImport } from './routes/ensaios.aniversarios'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnsaiosCasuaisRoute = EnsaiosCasuaisRouteImport.update({
  id: '/ensaios/casuais',
  path: '/ensaios/casuais',
  getParentRoute: () => rootRouteImport,
} as any)
const EnsaiosCasaisRoute = EnsaiosCasaisRouteImport.update({
  id: '/ensaios/casais',
  path: '/ensaios/casais',
  getParentRoute: () => rootRouteImport,
} as any)
const EnsaiosAniversariosRoute = EnsaiosAniversariosRouteImport.update({
  id: '/ensaios/aniversarios',
  path: '/ensaios/aniversarios',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contacto': typeof ContactoRoute
  '/portfolio': typeof PortfolioRoute
  '/privacidade': typeof PrivacidadeRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/ensaios/aniversarios': typeof EnsaiosAniversariosRoute
  '/ensaios/casais': typeof EnsaiosCasaisRoute
  '/ensaios/casuais': typeof EnsaiosCasuaisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contacto': typeof ContactoRoute
  '/portfolio': typeof PortfolioRoute
  '/privacidade': typeof PrivacidadeRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/ensaios/aniversarios': typeof EnsaiosAniversariosRoute
  '/ensaios/casais': typeof EnsaiosCasaisRoute
  '/ensaios/casuais': typeof EnsaiosCasuaisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contacto': typeof ContactoRoute
  '/portfolio': typeof PortfolioRoute
  '/privacidade': typeof PrivacidadeRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/ensaios/aniversarios': typeof EnsaiosAniversariosRoute
  '/ensaios/casais': typeof EnsaiosCasaisRoute
  '/ensaios/casuais': typeof EnsaiosCasuaisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/como-funciona'
    | '/contacto'
    | '/portfolio'
    | '/privacidade'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sobre'
    | '/ensaios/aniversarios'
    | '/ensaios/casais'
    | '/ensaios/casuais'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/como-funciona'
    | '/contacto'
    | '/portfolio'
    | '/privacidade'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sobre'
    | '/ensaios/aniversarios'
    | '/ensaios/casais'
    | '/ensaios/casuais'
  id:
    | '__root__'
    | '/'
    | '/como-funciona'
    | '/contacto'
    | '/portfolio'
    | '/privacidade'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sobre'
    | '/ensaios/aniversarios'
    | '/ensaios/casais'
    | '/ensaios/casuais'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ContactoRoute: typeof ContactoRoute
  PortfolioRoute: typeof PortfolioRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  EnsaiosAniversariosRoute: typeof EnsaiosAniversariosRoute
  EnsaiosCasaisRoute: typeof EnsaiosCasaisRoute
  EnsaiosCasuaisRoute: typeof EnsaiosCasuaisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ensaios/casuais': {
      id: '/ensaios/casuais'
      path: '/ensaios/casuais'
      fullPath: '/ensaios/casuais'
      preLoaderRoute: typeof EnsaiosCasuaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ensaios/casais': {
      id: '/ensaios/casais'
      path: '/ensaios/casais'
      fullPath: '/ensaios/casais'
      preLoaderRoute: typeof EnsaiosCasaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ensaios/aniversarios': {
      id: '/ensaios/aniversarios'
      path: '/ensaios/aniversarios'
      fullPath: '/ensaios/aniversarios'
      preLoaderRoute: typeof EnsaiosAniversariosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ContactoRoute: ContactoRoute,
  PortfolioRoute: PortfolioRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  EnsaiosAniversariosRoute: EnsaiosAniversariosRoute,
  EnsaiosCasaisRoute: EnsaiosCasaisRoute,
  EnsaiosCasuaisRoute: EnsaiosCasuaisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
